### ISSUE TITLE
Big idea

### ISSUE THREAD

**Issue by hakuno** [firevel/firevel#15]
It's not an issue :smile: :trophy: 

I didn't use it yet. But I hope I will.

Anyway, it's awesome!

If we don't want to pay for Laravel Vapor...
If we don't want to run on AWS...

So we can do with Firevel for free at GCP.

Brilliant! Keep it up.

**Comment by fgilio** [comment]
Indeed, this is a really interesting idea.

**Comment by sl0wik** [comment]
Thanks! I'm working on Firevel 6.0 which should be perfect for serverless microservices.
