### ISSUE TITLE
Any plans for Laravel 6?

### ISSUE THREAD

**Issue by george-kar** [firevel/firevel#17]
Any plans to support Laravel 6 instead of 5.8?

**Comment by sl0wik** [comment]
Yes. I'm working on new version based on Laravel 6. The key improvement going to be better CI/CD handling (it will likely come with gitlab ci setup).

It might contain one breaking change in ref to Firestore namespaces (using environment name as collection root), but migration should be simple.

**Comment by george-kar** [comment]
Great :) Any ETA?

**Comment by sl0wik** [comment]
I would say January. Perhaps earlier.

**Comment by sl0wik** [comment]
@george-kar master is now on Laravel 6. I will release a new version soon. If you are updating, all you need to do is: https://github.com/firevel/firevel/pull/18/commits/1aa0832149be03aa74e84a2149f166992da04f50
