### ISSUE TITLE
Laravel 7 and continuing?

### ISSUE THREAD

**Issue by necrogami** [firevel/firevel#28]
With laravel 7 out and taylors plans for faster updates is there any plans for this to continue staying up to date with base laravel?

**Comment by sl0wik** [comment]
The project will continue for sure. There is one blocker I'm fighting with for months.

The new version should work very well locally with a docker setup and local Firestore, but https://github.com/GoogleCloudPlatform/php-docker/issues/467 is blocking me with 7.0 release.

Feel free to upvote them. If they are not going to be resolved I will do 6.0 release

**Comment by sl0wik** [comment]
Laravel 7 update is merged to master branch.

**Comment by necrogami** [comment]
And now as of yesterday laravel 8 has been released.
